[project]
name = "patient-education-assistant-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "elasticsearch>=8.10.0",
    "faiss-cpu>=1.7.4",
    "fastapi[standard]>=0.104.0",
    "gradio>=3.35.0",
    "lxml>=4.9.0",
    "nltk>=3.8.0",
    "numpy>=1.24.0",
    "pandas>=2.1.0",
    "pypdf2>=3.0.0",
    "python-docx>=0.8.11",
    "python-multipart>=0.0.6",
    "requests>=2.31.0",
    "scikit-learn>=1.3.0",
    "sentence-transformers>=2.2.2",
    "spacy>=3.7.0",
    "torch>=2.0.0",
    "transformers>=4.35.0",
    "uvicorn[standard]>=0.24.0",
]
