[project]
name = "patient-education-assistant-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "biopython>=1.85",
    "jupyterlab>=0.2.4",
    "dotenv>=0.9.9",
    "elasticsearch>=8.10.0",
    "faiss-cpu>=1.7.4",  # Using CPU version as GPU version not available for this CUDA
    "fastapi[standard]>=0.104.0",
    "gradio>=3.35.0",
    "ipykernel>=6.30.0",
    "lxml>=4.9.0",
    "nltk>=3.8.0",
    "numpy>=1.24.0",
    "pandas>=2.1.0",
    "pypdf2>=3.0.0",
    "pytest-playwright>=0.7.0",
    "python-docx>=0.8.11",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.6",
    "requests>=2.31.0",
    "scikit-learn>=1.3.0",
    "sentence-transformers>=2.2.2",
    "spacy>=3.7.0",
    # "torch>=2.0.0",  # Provided by RunPod PyTorch template
    "transformers>=4.35.0",
    "uvicorn[standard]>=0.24.0",
    "accelerate>=0.20.0",  # For optimized GPU training and inference
    "datasets>=2.14.0",   # For efficient data loading
]

[project.optional-dependencies]
gpu = [
    "faiss-gpu>=1.7.4",
    "torch-audio",  # Additional PyTorch components
    "torchvision",
]

dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "jupyter>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["config", "scripts", "data"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 88
